/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as YearIndexImport } from './routes/$year/index'
import { Route as YearDaysDayImport } from './routes/$year/days/$day'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const YearIndexRoute = YearIndexImport.update({
  id: '/$year/',
  path: '/$year/',
  getParentRoute: () => rootRoute,
} as any)

const YearDaysDayRoute = YearDaysDayImport.update({
  id: '/$year/days/$day',
  path: '/$year/days/$day',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$year/': {
      id: '/$year/'
      path: '/$year'
      fullPath: '/$year'
      preLoaderRoute: typeof YearIndexImport
      parentRoute: typeof rootRoute
    }
    '/$year/days/$day': {
      id: '/$year/days/$day'
      path: '/$year/days/$day'
      fullPath: '/$year/days/$day'
      preLoaderRoute: typeof YearDaysDayImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$year': typeof YearIndexRoute
  '/$year/days/$day': typeof YearDaysDayRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$year': typeof YearIndexRoute
  '/$year/days/$day': typeof YearDaysDayRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$year/': typeof YearIndexRoute
  '/$year/days/$day': typeof YearDaysDayRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$year' | '/$year/days/$day'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$year' | '/$year/days/$day'
  id: '__root__' | '/' | '/$year/' | '/$year/days/$day'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YearIndexRoute: typeof YearIndexRoute
  YearDaysDayRoute: typeof YearDaysDayRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YearIndexRoute: YearIndexRoute,
  YearDaysDayRoute: YearDaysDayRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$year/",
        "/$year/days/$day"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$year/": {
      "filePath": "$year/index.tsx"
    },
    "/$year/days/$day": {
      "filePath": "$year/days/$day.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
